### POST Cadstrar ###

POST https://localhost:5001/api/contas/cadastrar
Content-Type: application/json

{
    "Nome" : "Luz",
    "Descricao" : "Conta de luz",
    "Valor" : 250.00,
    "DataVencimento" :  "2022-09-25T08:00:00.000Z",
    "Status" : false
}

### Get Listar ###
GET https://localhost:5001/api/contas/listar

### Alterar informar ID no JSON ###
PATCH https://localhost:5001/api/contas/alterar/
Content-Type: application/json

{
    "id" : "4",
    "Nome" : "Internet Móvel",
    "Descricao" : "Conta de internet Móvel",
    "Valor" : 150.00,
    "DataVencimento" :  "2022-09-10T08:00:00.000Z",
    "Status" : true
}

### Deletar /deletar/ID ###
DELETE https://localhost:5001/api/contas/deletar/6